/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.vista;

import itson.control.CompraControl;
import itson.modelo.Producto;
import java.util.List;

/**
 *
 * @author santi
 */
public class PnlCarrito extends javax.swing.JPanel {

    private CompraControl control;
          
    public PnlCarrito(CompraControl control) {
        initComponents();
        this.control = control;
        mostrarCantidades();
    }

    public void mostrarCantidades(){
    
        int cantBanana = 0;
        int cantManzana = 0;
        int cantToronja = 0;
        
        for(Producto producto : control.regresarCarrito()){
        
            if (producto.getNombre().equals("Manzana"))
                cantManzana++;
        
            if (producto.getNombre().equals("Banana"))
                cantBanana++;
        
            if (producto.getNombre().equals("Toronja"))
                cantToronja++;
        
        }
        
        lblCantBanana.setText(String.valueOf(cantBanana));
        lblCantManzana.setText(String.valueOf(cantManzana));
        lblCantToronja.setText(String.valueOf(cantToronja));
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblToronja = new javax.swing.JLabel();
        lblManzana = new javax.swing.JLabel();
        lblBanana = new javax.swing.JLabel();
        lblCantToronja = new javax.swing.JLabel();
        lblCantManzana = new javax.swing.JLabel();
        lblCantBanana = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblToronja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toronja.png"))); // NOI18N
        add(lblToronja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 110));

        lblManzana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manzana.png"))); // NOI18N
        add(lblManzana, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 110));

        lblBanana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banana.png"))); // NOI18N
        lblBanana.setText("jLabel1");
        add(lblBanana, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 100, 100));

        lblCantToronja.setText("$50");
        add(lblCantToronja, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        lblCantManzana.setText("$100");
        add(lblCantManzana, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        lblCantBanana.setText("$150");
        add(lblCantBanana, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBanana;
    private javax.swing.JLabel lblCantBanana;
    private javax.swing.JLabel lblCantManzana;
    private javax.swing.JLabel lblCantToronja;
    private javax.swing.JLabel lblManzana;
    private javax.swing.JLabel lblToronja;
    // End of variables declaration//GEN-END:variables
}
