/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.vista;

import itson.control.CompraControl;
import itson.modelo.Producto;

/**
 *
 * @author santi
 */
public class PnlFrutas extends javax.swing.JPanel {

    private CompraControl control;
          
    public PnlFrutas(CompraControl control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblToronja = new javax.swing.JLabel();
        lblManzana = new javax.swing.JLabel();
        lblBanana = new javax.swing.JLabel();
        cmbToronja = new javax.swing.JComboBox<>();
        cmbManzana = new javax.swing.JComboBox<>();
        cmbBanana = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblToronja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toronja.png"))); // NOI18N
        add(lblToronja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 110));

        lblManzana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manzana.png"))); // NOI18N
        add(lblManzana, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 110));

        lblBanana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banana.png"))); // NOI18N
        lblBanana.setText("jLabel1");
        add(lblBanana, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 100, 100));

        cmbToronja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        add(cmbToronja, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        cmbManzana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        add(cmbManzana, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        cmbBanana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        add(cmbBanana, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        btnAgregar.setText("Agregar al carrito");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel1.setText("$50");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel2.setText("$100");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel3.setText("$150");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        int cantBananas = cmbBanana.getSelectedIndex();
        int cantManzana = cmbManzana.getSelectedIndex();
        int cantToronja = cmbToronja.getSelectedIndex();
        
        Producto banana = new Producto("Banana", 150);
        Producto manzana = new Producto("Manzana", 100);
        Producto toronja = new Producto("Toronja", 50);
        
        
        if(cantBananas > 0)
            control.seleccionarProducto(banana, cantBananas);
        
        if(cantManzana > 0)
            control.seleccionarProducto(manzana, cantManzana);
        
        if(cantToronja > 0)
            control.seleccionarProducto(toronja, cantToronja);
        
       
        
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbBanana;
    private javax.swing.JComboBox<String> cmbManzana;
    private javax.swing.JComboBox<String> cmbToronja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBanana;
    private javax.swing.JLabel lblManzana;
    private javax.swing.JLabel lblToronja;
    // End of variables declaration//GEN-END:variables
}
