/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.vista;

import itson.control.CompraControl;
import itson.modelo.Producto;
import java.util.List;

/**
 *
 * @author santi
 */
public class PnlPago extends javax.swing.JPanel {

    private CompraControl control;
    private double monto;
          
    public PnlPago(CompraControl control) {
        initComponents();
        this.control = control;
        getMonto();
        
    }
    
    public void getMonto(){
    
        monto = control.procesarPago();
        lblMonto.setText(String.valueOf(monto));
        
        lblProductos.setVisible(false);
        lblCompraRealizada.setVisible(false);
        lblDatosBancarios.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();
        fldTarjeta = new javax.swing.JTextField();
        btnProcesarPago = new javax.swing.JButton();
        lblTituloMonto = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblCompraRealizada = new javax.swing.JLabel();
        lblDatosBancarios = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto.setText("Ingresa tu tarjeta bancaria");
        add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 460, -1));
        add(fldTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 320, -1));

        btnProcesarPago.setText("Procesar Pago");
        btnProcesarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarPagoActionPerformed(evt);
            }
        });
        add(btnProcesarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        lblTituloMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMonto.setText("Monto");
        add(lblTituloMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 100, 470, 20));

        lblMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonto.setText("PLACEHOLDER");
        add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 460, -1));

        lblCompraRealizada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompraRealizada.setText("La compra ha sido realizada con ");
        add(lblCompraRealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 180, 470, -1));

        lblDatosBancarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatosBancarios.setText("PLACEHOLDER");
        add(lblDatosBancarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 210, 470, -1));

        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductos.setText("PLACEHOLDER");
        add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 240, 470, -1));
    }// </editor-fold>//GEN-END:initComponents

    public String carritoString(List<Producto> items){
 


        java.util.Map<String, Integer> conteo = new java.util.LinkedHashMap<>();
        for (Producto prod : items) {
            String nombre = prod.getNombre();
            conteo.put(nombre, conteo.getOrDefault(nombre, 0) + 1);
        }

        StringBuilder sb = new StringBuilder("El carrito contiene: ");
        java.util.List<String> claves = new java.util.ArrayList<>(conteo.keySet());

        for (int i = 0; i < claves.size(); i++) {
            String nombre = claves.get(i);
            int cantidad = conteo.get(nombre);

            sb.append(cantidad).append(" ").append(nombre);

            if (i < claves.size() - 1) {
                sb.append(", ");
            } else {
                sb.append(".");
            }
        }

        return sb.toString();
        
    }
    
    public void llenarDatosPago(String tarjeta){
    
        lblTexto.setVisible(false);
        fldTarjeta.setVisible(false);
        lblTituloMonto.setVisible(false);
        
        lblProductos.setVisible(true);
        lblCompraRealizada.setVisible(true);
        lblDatosBancarios.setVisible(true);
        
        String datosBancarios = "La tarjeta : " + fldTarjeta.getText() + " del tipo " + tarjeta + " fue aceptada!";
        String productos = carritoString(control.regresarCarrito());
        lblProductos.setText(productos);
        lblDatosBancarios.setText(datosBancarios);
        control.reiniciarCarrito();
        
    }
    
    private void btnProcesarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarPagoActionPerformed
        
        String tarjeta = control.ingresarNumeroTarjeta(fldTarjeta.getText());
        
        if (tarjeta.equals("INVALID") || tarjeta.equals("ERROR")) {
            javax.swing.JOptionPane.showMessageDialog(
                this,                            
                "El número de tarjeta ingresado no es válido o hubo un error al procesar.",
                "Error de Pago",                
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } else {
            
            llenarDatosPago(tarjeta);
            
        }
    }//GEN-LAST:event_btnProcesarPagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesarPago;
    private javax.swing.JTextField fldTarjeta;
    private javax.swing.JLabel lblCompraRealizada;
    private javax.swing.JLabel lblDatosBancarios;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTituloMonto;
    // End of variables declaration//GEN-END:variables
}
